name: Python Tests

on:
    push:
        branches:
            - '*'
    pull_request:
        branches:
            - main

jobs:
    black:
        runs-on: ubuntu-latest
        steps:
            - name: Check out code
              uses: actions/checkout@v4

            - name: Run black
              uses: psf/black@stable
              with:
                options: "--check --verbose ."
                version: "~=24.4.0"

    pylint:
        runs-on: ubuntu-latest
        steps:
            - name: Check out code
              uses: actions/checkout@v4

            - name: Run pylint
              run: |
                pip install -r tests/requirements.txt  # Install test dependencies
                python -m pylint --fail-under=7 .

    pytest:
        runs-on: ubuntu-latest
        steps:
            - name: Check out code
              uses: actions/checkout@v4

            - name: Run pytest tests
              run: |
                pip install -r tests/requirements.txt  # Install test dependencies
                python -m pytest tests/functional_tests.py  # Run functional tests

