name: Python Tests

on:
    push:
        branches:
            - main
            - 'feature/*'
    pull_request:
        branches:
            - main

jobs:
    # test:
    #     runs-on: ubuntu-latest

    #     steps:
    #         - uses: actions/checkout@v2
    #         - name: Set up Python 3.9
    #           uses: actions/setup-python@v2
    #           with:
    #               python-version: 3.9

    #         - name: Install dependencies
    #           run: |
    #               python -m pip install --upgrade pip
    #               pip install -r requirements.txt

    #         - name: Run black
    #           run: |
    #               python -m black .

    #         - name: Run pylint
    #           run: |
    #               python -m pylint .

    #         - name: Run pytest tests
    #           run: |
    #               python -m pytest tests/

    black:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Set up Python 3.9
              uses: actions/setup-python@v2
              with:
                python-version: 3.9
            - name: Install dependencies
              run: |
                python -m pip install --upgrade pip
                pip install -r requirements.txt
            - name: Run black
              run: |
                python -m black .

    pylint:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Set up Python 3.9
              uses: actions/setup-python@v2
              with:
                python-version: 3.9
            - name: Install dependencies
              run: |
                python -m pip install --upgrade pip
                pip install -r requirements.txt
            - name: Run pylint
              run: |
                python -m pylint . || true  # Allow pylint to pass even if the score is not 10/10

    pytest:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Set up Python 3.9
              uses: actions/setup-python@v2
              with:
                python-version: 3.9
            - name: Install dependencies
              run: |
                python -m pip install --upgrade pip
                pip install -r requirements.txt
            - name: Run pytest tests
              run: |
                python -m pytest tests/

