name: Python Tests

on:
    push:
        branches:
            - '*'
    pull_request:
        branches:
            - main

jobs:
    black:
        runs-on: ubuntu-latest
        steps:
            - name: Check out code
              uses: actions/checkout@v4

            - name: Run black
              uses: psf/black@stable
              with:
                options: "--check --verbose ."
                version: "~=24.4.0"

    pylint:
        runs-on: ubuntu-latest
        steps:
            - name: Check out code
              uses: actions/checkout@v4

            - name: Run pylint
              run: |
                pip install -r tests/requirements.txt  # Install test dependencies
                python -m pylint --fail-under=7 --disable=C0114,C0415,R0913,R0917,C0301,R0914,R0911,R0912,R0915,W0613,W1203,C0302,R0904,C0103 .

    pytest:
        runs-on: ubuntu-latest
        steps:
            - name: Check out code
              uses: actions/checkout@v4

            - name: Run pytest tests
              run: |
                pip install -r tests/requirements.txt  # Install test dependencies
                python -m pytest tests/functional_tests.py  # Run functional tests

